# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtGui import QIcon, QStandardItem
from PyQt5.QtGui import QStandardItemModel
from typing import Union


class UiMain(object):
    def __init__(self, main):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        self.model = QStandardItemModel()
        self.fnum = 0
        self.target = None
        self.exit = QtWidgets.QPushButton(main)
        self.exit.setGeometry(QtCore.QRect(560, 410, 80, 20))
        self.exit.setObjectName("exit")
        self.start = QtWidgets.QPushButton(main)
        self.start.setGeometry(QtCore.QRect(650, 410, 80, 20))
        self.start.setObjectName("start")
        self.thread_num_slider = QtWidgets.QSlider(main)
        self.thread_num_slider.setGeometry(QtCore.QRect(10, 320, 160, 22))
        self.thread_num_slider.setMaximum(200)
        self.thread_num_slider.setOrientation(QtCore.Qt.Horizontal)
        self.thread_num_slider.setObjectName("thread_num_slider")
        self.icmp = QtWidgets.QRadioButton(main)
        self.icmp.setGeometry(QtCore.QRect(20, 110, 80, 20))
        self.icmp.setObjectName("icmp")
        self.get = QtWidgets.QRadioButton(main)
        self.get.setGeometry(QtCore.QRect(20, 70, 80, 20))
        self.get.setObjectName("get")
        self.syn = QtWidgets.QRadioButton(main)
        self.syn.setGeometry(QtCore.QRect(20, 90, 80, 20))
        self.syn.setObjectName("syn")
        self.protocol_sel = QtWidgets.QLabel(main)
        self.protocol_sel.setGeometry(QtCore.QRect(15, 40, 201, 20))
        self.protocol_sel.setObjectName("protocol_sel")
        self.thread_num = QtWidgets.QLCDNumber(main)
        self.thread_num.setGeometry(QtCore.QRect(10, 250, 160, 61))
        self.thread_num.setFrameShape(QtWidgets.QFrame.Box)
        self.thread_num.setSmallDecimalPoint(True)
        self.thread_num.setMode(QtWidgets.QLCDNumber.Dec)
        self.thread_num.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.thread_num.setObjectName("thread_num")
        self.thread_sel = QtWidgets.QLabel(main)
        self.thread_sel.setGeometry(QtCore.QRect(10, 170, 190, 20))
        self.thread_sel.setObjectName("thread_sel")
        self.thread_info = QtWidgets.QLabel(main)
        self.thread_info.setGeometry(QtCore.QRect(10, 190, 210, 20))
        self.thread_info.setObjectName("thread_info")
        self.logger = QtWidgets.QListView(main)
        self.logger.setGeometry(QtCore.QRect(520, 10, 250, 350))
        self.logger.setObjectName("logger")
        self.logger.setAutoScroll(True)
        self.label = QtWidgets.QLabel(main)
        self.label.setGeometry(QtCore.QRect(10, 210, 351, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(main)
        self.label_2.setGeometry(QtCore.QRect(10, 230, 191, 16))
        self.label_2.setObjectName("label_2")
        self.ip = QtWidgets.QLineEdit(main)
        self.ip.setGeometry(QtCore.QRect(222, 60, 161, 20))
        self.ip.setMaxLength(15)
        self.ip.setObjectName("ip")
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setGeometry(QtCore.QRect(220, 40, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(main)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(220, 170, 281, 21))
        self.label_4.setObjectName("label_4")
        self.port = QtWidgets.QLineEdit(main)
        self.port.setEnabled(False)
        self.port.setGeometry(QtCore.QRect(230, 190, 113, 20))
        self.port.setMaxLength(5)
        self.port.setObjectName("port")
        self.packet_num = QtWidgets.QLCDNumber(main)
        self.packet_num.setGeometry(QtCore.QRect(220, 260, 160, 61))
        self.packet_num.setFrameShape(QtWidgets.QFrame.Box)
        self.packet_num.setSmallDecimalPoint(True)
        self.packet_num.setMode(QtWidgets.QLCDNumber.Dec)
        self.packet_num.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.packet_num.setProperty("value", 0.0)
        self.packet_num.setObjectName("packet_num")
        self.label_5 = QtWidgets.QLabel(main)
        self.label_5.setGeometry(QtCore.QRect(210, 240, 191, 16))
        self.label_5.setObjectName("label_5")
        self.dial = QtWidgets.QDial(main)
        self.dial.setGeometry(QtCore.QRect(240, 330, 121, 101))
        self.dial.setMaximum(100000)
        self.dial.setSingleStep(100)
        self.dial.setPageStep(100)
        self.dial.setObjectName("packet_dial")
        self.progressBar = QtWidgets.QProgressBar(main)
        self.progressBar.setGeometry(QtCore.QRect(530, 370, 260, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("p_bar")
    
        self.retranslateUi(main)
        self.thread_num_slider.valueChanged['int'].connect(self.thread_num.display)
        self.exit.clicked.connect(main.close)
        self.syn.clicked['bool'].connect(self.port.setEnabled)
        self.syn.clicked['bool'].connect(self.label_4.setEnabled)
        self.dial.valueChanged['int'].connect(self.packet_num.display)
        self.start.clicked.connect(self.select)
        self.dial.actionTriggered['int'].connect(self.progressBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(main)

    @staticmethod
    def setupUi(main):
        main.setObjectName("main")
        main.resize(780, 450)
        icon = QtGui.QIcon.fromTheme("icon")
        main.setWindowIcon(icon)
        QtCore.QMetaObject.connectSlotsByName(main)

    def select(self):
        for i in range(1000):
            self.logging(str(i))
        
    def logging(self, item):
        self.model.appendRow(QStandardItem(item))
        self.logger.setModel(self.model)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Netflooder"))
        self.exit.setText(_translate("main", "나가기"))
        self.start.setText(_translate("main", "시작하기"))
        self.icmp.setText(_translate("main", "ICMP"))
        self.get.setText(_translate("main", "HTTP Get"))
        self.syn.setText(_translate("main", "SYN"))
        self.protocol_sel.setText(_translate("main", "1. Flooding 방식을 선택해 주세요"))
        self.thread_sel.setText(_translate("main", "2. 사용할 스레드 수를 선택하세요"))
        self.thread_info.setText(_translate("main", "1스레드당 약 8MB의 램을 사용합니다."))
        self.label.setText(_translate("main", "100개 이상의 스레드 사용시에는 "))
        self.label_2.setText(_translate("main", "심각한 렉이 발생할수 있습니다"))
        self.ip.setPlaceholderText(_translate("main", "ex) 123.456.789.123"))
        self.label_3.setText(_translate("main", "3. 대상의 ip를 입력해 주세요"))
        self.label_4.setText(_translate("main", "4. SYN 프로토콜일 경우 포트 번호를 입력해 주세요"))
        self.port.setPlaceholderText(_translate("main", "ex) 0 - 65535"))
        self.label_5.setText(_translate("main", "5. 보낼 패킷 갯수를 입력해 주세요."))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMain(MainWindow)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())